name: shopapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  carousel_pro: ^0.0.13
  flutter:
    sdk: flutter
  cloud_firestore:
  firebase_auth:
  google_sign_in:
  flutter_bloc:
  bloc:
  equatable:
  meta:
  font_awesome_flutter:
  firebase_core:
  shared_preferences:
  lombok:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/c1.jpg
    - images/m1.jpeg
    - images/w3.jpeg
    - images/w4.jpeg
    - images/m2.jpg
    - images/cats/tshirt.png
    - images/cats/dress.png
    - images/cats/formal.png
    - images/cats/informal.png
    - images/cats/shoe.png
    - images/cats/jeans.png
    - images/cats/accessories.png
    - images/products/image_01.png
    - images/products/image_02.png
    - images/products/image_03.png
    - images/products/image_04.png
    - images/products/image_05.png
    - images/products/image_05.jpg
    - images/droplet.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Black.ttf
        - asset: fonts/Raleway/Raleway-BlackItalic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Black.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700

    - family: Montserrat-Bold
      fonts:
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: Montserrat-Black
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf

    - family: Montserrat-Medium
      fonts:
        - asset: fonts/Montserrat/Montserrat-Medium.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
